### PR TITLE
day1 solution added

### PR DESCRIPTION
**Pull request by AryanKansagara**
I have solved the day1 problem the file contains the function getArea and getPerimeter in which the code has to be added in the solution

### CODE REVIEW

**Review by ayush-geeks — APPROVED** [review]

**Review by ayush-geeks — APPROVED** [review]
👍

**Review by ayush-pr0 — APPROVED** [review]
Nice work

**Comment by AryanKansagara** [comment]
Yeah Surely i would we can also connect maybe I can also help you in creating such repos and be a maintainer

**Comment by ayush-pr0** [comment]
> Yeah Surely i would we can also connect maybe I can also help you in creating such repos and be a maintainer

👍

**Pull request merged**
