### PR TITLE
day 9 completed

### LINKED ISSUE #11: Solve Day 9 Problems

### PR DESCRIPTION
**Pull request by Teddy1404**
This closes #11

### CODE REVIEW

**Comment by ayush-pr0** [comment]
1. Update the file name to the original problem name.
  Ex: Problem name: Hello, World!
  So the file name must be HelloWorld.js
2. Do not paste/write the whole code...you need to paste/write the function which is given in the problem to complete.
3. Also add the HTML and CSS file if problem is asking for the same

**Comment by Teddy1404** [comment]
@ayush-pr0 done as you said

**Review by ayush-pr0 — CHANGES_REQUESTED** [review]
Day 9 solution is accepted...but in Day 2 solutions you don't have pasted whole code.

Let me explain, In In-Else problem only getGrade() function is required, Similarly you have to make changes in other solutions of Day 2. (Remove the redundant code).

**Comment by ayush-pr0** [comment]
@Teddy1404 I have assigned you this task. Try to complete it as soon as possible.

**Comment by Teddy1404** [comment]
I updated day 2

**Review by ayush-pr0 — APPROVED** [review]
Good work 👍

**Comment by ayush-pr0** [comment]
@Teddy1404 
Follow me for more such projects. It will motivate me to start more such easy projects for you guys.

**Pull request merged**
