### PR TITLE
Added Day 3

### PR DESCRIPTION
**Pull request by ProtyayMnd50**

### CODE REVIEW

**Comment by ProtyayMnd50** [comment]
Added  my pr, @ayush-pr0 , you can review it.

**Review by ayush-pr0 — COMMENTED** [review]
Code which is in comment is not required. In Try_Catch.js, try to use finally block in it.

**Comment by ayush-pr0** [comment]
@ProtyayMnd50 follow me for more such repo. Soon I'll create a repo on Leetcode problem set. If you are interested then you can contribute in the same:)

**Review by ayush-pr0 — APPROVED** [review]
Good Work 👍

**Comment by ProtyayMnd50** [comment]
Looking forward to work more with you!

**Pull request merged**
